name: Code Validation

on:
  push:
    branches:
      - main

jobs:
  Run-Code-Validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: configure ssh
        run: |
          mkdir ~/.ssh
          echo "Host github.com" >> ~/.ssh/config
          echo "        Hostname github.com" >> ~/.ssh/config
          echo "        IdentityFile={{github.workspace}}/gh_deploy_key" >> ~/.ssh/config
          echo $SSH_GITHUB_DEPLOY_KEY >> {{github.workspace}}/gh_deploy_key
      - name: Deploy Site
        run: poetry run mkdocs gh-deploy --force --clean --verbose
